<?php
$kong_popup_supports = array(
	'locale' 		=> get_locale(),
	'admin_url'		=> admin_url( 'admin.php' ),
	'ajax_url' 		=> admin_url( 'admin-ajax.php' ),
	'base_url' 		=> PLUGIN_BASE_URL,
	'current_page' 	=> ( isset( $_REQUEST[ 'page' ] ) ) ? $_REQUEST[ 'page' ] : "",
	// 'apply' 		=> __( 'Apply', 'kong-popup' ),
	// 'cancel' 		=> __( 'Cancel', 'kong-popup' ),
	// 'from' 			=> __( 'from', 'kong-popup' ),
	// 'to' 			=> __( 'to', 'kong-popup' ),
	// 'today' 		=> __( 'Today', 'kong-popup' ),
	// 'yesterday' 	=> __( 'Yesterday', 'kong-popup' ),
	// 'tomorrow' 		=> __( 'Tomorrow', 'kong-popup' ),
	// 'last_7_days' 	=> __( 'Last 7 Days', 'kong-popup' ),
	// 'last_30_days' 	=> __( 'Last 30 Days', 'kong-popup' ),
	// 'this_month' 	=> __( 'This Month', 'kong-popup' ),
	// 'next_month' 	=> __( 'Next Month', 'kong-popup' ),
	// 'custom_range' 	=> __( 'Custom Range', 'kong-popup' ),
);